package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCredit;
import org.linlinjava.litemall.db.domain.LitemallCreditExample;

public interface LitemallCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    long countByExample(LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int insert(LitemallCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    LitemallCredit selectOneByExample(LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    LitemallCredit selectOneByExampleSelective(@Param("example") LitemallCreditExample example, @Param("selective") LitemallCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    List<LitemallCredit> selectByExampleSelective(@Param("example") LitemallCreditExample example, @Param("selective") LitemallCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    List<LitemallCredit> selectByExample(LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    LitemallCredit selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    LitemallCredit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCredit record, @Param("example") LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCredit record, @Param("example") LitemallCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCredit record);
}