package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TbCompany;
import org.linlinjava.litemall.db.domain.TbCompanyExample;

public interface TbCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    long countByExample(TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int deleteByExample(TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int insert(TbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int insertSelective(TbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    TbCompany selectOneByExample(TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    TbCompany selectOneByExampleSelective(@Param("example") TbCompanyExample example, @Param("selective") TbCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    List<TbCompany> selectByExampleSelective(@Param("example") TbCompanyExample example, @Param("selective") TbCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    List<TbCompany> selectByExample(TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    TbCompany selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    TbCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbCompany record, @Param("example") TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbCompany record, @Param("example") TbCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCompany record);
}