package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class LitemallStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.corporation
     *
     * @mbg.generated
     */
    private String corporation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.telephone
     *
     * @mbg.generated
     */
    private Integer telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.mobile
     *
     * @mbg.generated
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.address
     *
     * @mbg.generated
     */
    private Integer address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.provience
     *
     * @mbg.generated
     */
    private String provience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.street
     *
     * @mbg.generated
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_store.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.id
     *
     * @return the value of litemall_store.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.id
     *
     * @param id the value for litemall_store.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.name
     *
     * @return the value of litemall_store.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.name
     *
     * @param name the value for litemall_store.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.corporation
     *
     * @return the value of litemall_store.corporation
     *
     * @mbg.generated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.corporation
     *
     * @param corporation the value for litemall_store.corporation
     *
     * @mbg.generated
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.telephone
     *
     * @return the value of litemall_store.telephone
     *
     * @mbg.generated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.telephone
     *
     * @param telephone the value for litemall_store.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.mobile
     *
     * @return the value of litemall_store.mobile
     *
     * @mbg.generated
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.mobile
     *
     * @param mobile the value for litemall_store.mobile
     *
     * @mbg.generated
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.address
     *
     * @return the value of litemall_store.address
     *
     * @mbg.generated
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.address
     *
     * @param address the value for litemall_store.address
     *
     * @mbg.generated
     */
    public void setAddress(Integer address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.provience
     *
     * @return the value of litemall_store.provience
     *
     * @mbg.generated
     */
    public String getProvience() {
        return provience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.provience
     *
     * @param provience the value for litemall_store.provience
     *
     * @mbg.generated
     */
    public void setProvience(String provience) {
        this.provience = provience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.city
     *
     * @return the value of litemall_store.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.city
     *
     * @param city the value for litemall_store.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.country
     *
     * @return the value of litemall_store.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.country
     *
     * @param country the value for litemall_store.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.street
     *
     * @return the value of litemall_store.street
     *
     * @mbg.generated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.street
     *
     * @param street the value for litemall_store.street
     *
     * @mbg.generated
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_store.app_id
     *
     * @return the value of litemall_store.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_store.app_id
     *
     * @param appId the value for litemall_store.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", corporation=").append(corporation);
        sb.append(", telephone=").append(telephone);
        sb.append(", mobile=").append(mobile);
        sb.append(", address=").append(address);
        sb.append(", provience=").append(provience);
        sb.append(", city=").append(city);
        sb.append(", country=").append(country);
        sb.append(", street=").append(street);
        sb.append(", appId=").append(appId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallStore other = (LitemallStore) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCorporation() == null ? other.getCorporation() == null : this.getCorporation().equals(other.getCorporation()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getProvience() == null ? other.getProvience() == null : this.getProvience().equals(other.getProvience()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getStreet() == null ? other.getStreet() == null : this.getStreet().equals(other.getStreet()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCorporation() == null) ? 0 : getCorporation().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getProvience() == null) ? 0 : getProvience().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getStreet() == null) ? 0 : getStreet().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_store
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        corporation("corporation", "corporation", "VARCHAR", false),
        telephone("telephone", "telephone", "INTEGER", false),
        mobile("mobile", "mobile", "INTEGER", false),
        address("address", "address", "INTEGER", false),
        provience("provience", "provience", "VARCHAR", false),
        city("city", "city", "VARCHAR", false),
        country("country", "country", "VARCHAR", false),
        street("street", "street", "VARCHAR", false),
        appId("app_id", "appId", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_store
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}